### ISSUE TITLE
Design website

### ISSUE THREAD

**Issue by isabela-pf** [conda-incubator/conda-dot-org#1]
I’ll be working on designing a website so that there is a consolidated and easy-to-find resource for the basics related to Conda’s community. This issue will record the process and feedback.

To provide a foundation for discussion and ensuring the website serves its purpose, here are the main reasons I think someone might visit this website once it exists:
- To understand what the Conda community and/or incubator is
- To answer questions about Conda community and/or an incubator project
- To find a project
- To find people working on these projects or leadership in general
- To find out how/what ways they are welcome to contribute

Please feel free to give feedback on these use cases or add more. These will be some of my main criteria for making design decisions, so the more accurate the goals, the better.

**Comment by jezdez** [comment]
In preparation for the work on a future conda.org this issue was moved into the new repo as requested in https://github.com/conda-incubator/governance/issues/76.

**Comment by tnabtaf** [comment]
The website [launched in April](https://conda.org/blog/2022-04-27-welcome-to-conda-dot-org).  Closing this issue.
