### ISSUE TITLE
Explain the problems conda solves under "what is Conda" page

### ISSUE THREAD

**Issue by electric-souperman** [conda-incubator/conda-dot-org#101]
## Description

I have a sense that a complete beginner will more readily understand what Conda *is* in terms of the problems it can solve for them, so I would propose putting some of the content on this in the FAQ up front in the "what is Conda?" page.

## Tasks

- [x] Add some content to the first para of learn/intro.md

**Comment by electric-souperman** [comment]
I've addressed this in PR: https://github.com/conda-incubator/conda-dot-org/pull/102

**Comment by travishathaway** [comment]
@electric-souperman,

We have removed this page, so this issue no longer makes sense. I will be closing this issue now.
