### ISSUE TITLE
Homepage displaying typo in description for March 30th Blog post

### ISSUE THREAD

**Issue by electric-souperman** [conda-incubator/conda-dot-org#103]
## Description

Aanconda.

![Screenshot 2023-04-24 110314](https://user-images.githubusercontent.com/63853472/234068004-eb3f9df4-8098-421f-a5ed-f1b863d157bb.png)

## Tasks

- [x] Address typo in markdown file for blog post
- [x] Address typo in `blog/news.json`

**Comment by electric-souperman** [comment]
Fixed: see PR https://github.com/conda-incubator/conda-dot-org/pull/104

**Comment by travishathaway** [comment]
Issue has been fixed. Thanks for your contribution @electric-souperman.
