### ISSUE TITLE
Glossary - Add definitions for Anaconda, Miniconda, and conda

### ISSUE THREAD

**Issue by beeankha** [conda-incubator/conda-dot-org#107]
## Description

Connecting issue https://github.com/conda-incubator/conda-dot-org/issues/111

Add the question "What is the difference between Anaconda, Miniconda, and conda?" to the conda.org FAQ ([learn/faq.md](https://conda.org/learn/faq)) and answer it.

**Comment by vasvi-sood** [comment]
@beeankha I would like to take this issue if that's ok.

**Comment by Bennykillua** [comment]
Hi, can I work on this

**Comment by beeankha** [comment]
Hi @vasvi-sood , @sitamgithub-MSIT , @Bennykillua and @bhavukkalra. Thank you for your time and willingness to contribute to this repository. This issue is not ready to be worked on since there needs to be discussion re: how to set up a Glossary page, where the glossary items will appear, etc. 

Please do not create draft PRs without being assigned to the issue first. [This message](https://matrix.to/#/!howeixcJvVovRnuQdX:matrix.org/$5FBUCHcupTMet5BP0MGo16JIg-9g9uRKjr5GJNwGkvw?via=matrix.org&via=gitter.im) from Element contains more details:
>For all the people who want to contribute, thank you for donating your time and energy, but **please do not work on anything you are not assigned to**. It is currently quite overwhelming for us to not only have to read over all the great applications that came in for GSoD but also having to manage a project where so many people wish to make contributions to. Just because you have started on something and have a draft ready, does not mean it will be more likely that you will ultimately be assigned the issue.
>
> We ask for everyone's patience going forward as we try to find the best work items for all of the volunteers.
>
> Thank you ✌️


Going forward, please keep a lookout for any issues labeled "good first issue" when they become available in the future.

**Comment by Bennykillua** [comment]
okay @beeankha Thanks for the feedback

**Comment by beeankha** [comment]
The different terms and names are explained [in this question on the FAQ](https://conda.org/learn/faq#why-does-conda-have-so-many-meanings-in-different-contexts); closing this issue as complete.
