### ISSUE TITLE
News Page: Design the news item index page

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#11]
## Description

The [news page](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#News) will be our first "[index](https://hackmd.io/ljHIgPXqQuimhTmQOPeh9g#Feed--Index-pages)" page.  These pages list items of a particular type (e.g., news, blog, events, etc.).

We need to figure out what news item metadata (#8) should be presented on the index pages, and how.  Should this be a table, a list, cards, what?

## Tasks

- [ ] Create wire frame using a tool like Figma or Adobe Illustrator (this will be handed to our implementation team later who will actually create the CSS/HTML)
- [ ] Share this wire frame here and get approval from the design team

**Comment by travishathaway** [comment]
@tnabtaf, I'm going to be closing this as we will not be including this on the website anytime soon.
