### ISSUE TITLE
Set up privacy focused web analytics

### ISSUE THREAD

**Issue by jezdez** [conda-incubator/conda-dot-org#113]
## Description

It's beneficial for website development to be able to refer to an ongoing analysis of web traffic. I would suggest adding an analytics product that is designed with privacy in mind at least and doesn't store any personal identifiable information. The account should be shareable with the website and infra teams.

## Tasks

- [ ] Research which platforms exist (rubric: privacy-friendly, affordable or free for OSS, easy to integrate in the website without lock-in into hoster)
- [ ] Implement site analytics

**Comment by jaimergp** [comment]
Since we are on netlify already, this might be nice: https://www.netlify.com/products/analytics/

**Comment by jezdez** [comment]
As I said above, we shouldn't use the hoster feature, in case we want to switch platforms. The data export story is usually not great for those included features, meaning that we wouldn't be able to track long-term.

**Comment by jezdez** [comment]
I like goatcounter's offering, and it supports data export.
