### ISSUE TITLE
Add link to analytics site in our site footer

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#119]
## Description

We recently added a public facing analytics site for conda dot org. We would like to link to this analytics dashboard from our website. This should be placed in the footer underneath the "More" section:

<img width="350" alt="Bildschirmfoto 2023-05-03 um 06 58 00" src="https://user-images.githubusercontent.com/718726/235835591-5ea75b41-82c8-45d5-8707-f23ad03cb537.png">

## Tasks

- [ ] Place a link to https://conda-dot-org.goatcounter.com/ and have the link text read "Analytics Dashboard" (it should be the last link listed).
- [ ] Make sure it has the external link icon next to it like the "GitHub" link.

**Comment by Avik-creator** [comment]
I want to work on it

**Comment by tayyab-ilyas** [comment]
can I create a pr?
