### ISSUE TITLE
Home Page: Design it

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#16]
## Description

The home page is special. It unifies the site and makes it easy for people to quickly find what they are looking for. It won't look like most content or index pages.

## Tasks

- [ ] Create wire frame using a tool like Figma or Adobe Illustrator (this will be handed to our implementation team later who will actually create the CSS/HTML)
- [ ] Share this wire frame here and get approval from the design team

**Comment by jaimergp** [comment]
@Asmit2952 - you can share your ideas here too!

**Comment by Asmit2952** [comment]
Thank you @jaimergp. These are my design iterations for home page. Do let me know your thoughts everyone :) 

## Mobile View
![home-mobile.png](https://user-images.githubusercontent.com/81866614/198878230-bd7f680f-a6a1-4950-b003-628466741f07.png)

## Desktop View 
![home.png](https://user-images.githubusercontent.com/81866614/198878219-16eaff69-76a5-46a3-8664-37a8f9b73deb.png)

**Comment by Asmit2952** [comment]
## Color Palette:

`#43B02A`
`#DCF0EF`
`#F3FFF3`
`#2DB24A`
`#1EB59A`
