### ISSUE TITLE
Home Page: Implement Final Design

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#17]
## Description

The home page is special. It unifies the site and makes it easy for people to quickly find what they are looking for. It won't look like most content or index pages.  Issue #16 will establish the design of the home page.  This issue implements the approved design.

## Tasks

- [x] Using the final design from the design team, implement the home page using the site style sheet.
- [x] Submit this for review via a pull request and iterate until everyone is satisfied.

**Comment by kirtanchandak** [comment]
Hey, can I work on this issue ?

**Comment by Asmit2952** [comment]
Hey @travishathaway ! Please assign this issue to me
