### ISSUE TITLE
Site Search: Settle on search technology

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/conda-dot-org#20]
## Description

The website needs a search function.  Ideally that search function would also search an identified list of other conda-related sites as well.  

## Tasks

- [x] Create a document in the [team's HackMD space](https://hackmd.io/team/conda-dot-org?nav=overview) for listing and discussing options. Post a link to that here.  Created.  [Link](https://hackmd.io/HBuhoWgcSgiey1zE_mMnbg).
- [ ] Discuss and decide on a search technology to use.  Post that decision here.

**Comment by tnabtaf** [comment]
[Page to cover search options has now been created in HackMD](https://hackmd.io/HBuhoWgcSgiey1zE_mMnbg).  Have at it.

**Comment by kalawac** [comment]
We'll be going with Algolia Search, via Algolia's [DocSearch program](https://docsearch.algolia.com/docs/what-is-docsearch/).
