### ISSUE TITLE
Setup the initial Docusaurus website

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#3]
## Description

Set up the initial Docusaurus website. We need this so that the designers and content creators can begin adding and modifying the website. When setting this up, we need to make sure that there are clear instructions for would-be developers to run this locally on their own computers. Running this website locally will be the primary way that we preview the work we are doing.

This will be a bare bones Docusaurus site and should use customizable friendly theme if one is available.

## Tasks

- [ ] Add Docusaurus to this repository with a theme designed for customizing
- [ ] Add instructions for how to run this locally

**Comment by sanyamjain04** [comment]
Hi @travishathaway, Can you please tell me How I can contribute to this Repo? 
I am a Mern Stack developer. I can help in code implementation.
I tried to join the slack group, but the invite link has expired.

**Comment by tnabtaf** [comment]
Hi @sanyamjain04, thanks for the heads up about the Slack invite.  I will update public links (which will then expire in 30 days, sigh).  In the meantime, please [use this link](https://join.slack.com/t/conda/shared_invite/zt-1ik6vglro-AdmjqKxjTbD7D0eRBfMr6A) to join.  Once you are in, there are four conda-dot-org groups.  Join the ones that interest you and then I'll get you added to all the relevant spaces.

Thanks for your interest!

**Comment by sanyamjain04** [comment]
Hi @tnabtaf, Thanks for sending the invite link. Can you please add me to the slack channel where I can involve in the discussion of the development of the website? (Sorry to bother you I am new to slack, and I can only see 3 channels )
![image](https://user-images.githubusercontent.com/107163858/197843221-92b39775-475b-45ec-b370-8b3df4184411.png)

**Comment by sanyamjain04** [comment]
@tnabtaf  Thank you so much for sending the invite link. Can you please tell me Can I work on this issue If @jaimergp may allow me?

**Comment by jaimergp** [comment]
See #22
