### ISSUE TITLE
Conda logo needs a redesign!

### ISSUE THREAD

**Issue by Asmit2952** [conda-incubator/conda-dot-org#44]
## Description

The current "C" from the Conda logo when viewed in the [deployment](https://conda-dot-org-previews.netlify.app/) has many inconsistencies. We will need a new/refreshed version of this logo to replace on the website and other marketing material. Attaching an image here for reference:

![Screenshot (448)](https://user-images.githubusercontent.com/81866614/217060747-92615f99-b17b-4ad2-a49a-369f35a38f75.png)

## Tasks

- [x] Redesign the Conda (C) logo.

**Comment by tnabtaf** [comment]
I will pursue this Anaconda graphic designers.

**Comment by tnabtaf** [comment]
@ang852 saves the day!

![conda-c-logo](https://user-images.githubusercontent.com/1622414/217089924-c6b6b902-a653-4441-a47e-4a0b09dd32ed.svg)

Speedy, she is.

**Comment by Asmit2952** [comment]
> @tnabtaf
> 
> Could we please get the SVG of this logo and not just the image? I'm going to see what other SVG resources I can track down myself too.
> 
> Also, @Asmit2952 do you think it's a good idea to render the SVG instead of the image on the website? I was thinking we could do the same for the conda logo itself in the site header once I find that SVG file.

I did try loading SVG instead of PNG, but faced a few issues before. Once we get the logo, I'll try it again. Here's the ref doc: https://docusaurus.io/docs/next/markdown-features/assets#inline-svgs

**Comment by tnabtaf** [comment]
@Asmit2952 

> Once we get the logo

Are you waiting on the PNG version?  If so, how big would you like it to be?

**Comment by Asmit2952** [comment]
> @Asmit2952
> 
> > Once we get the logo
> 
> Are you waiting on the PNG version? If so, how big would you like it to be?

PNG would do good for now, but Travis and Jaime suggested on using SVG. If I get the SVG, I can experiment with it and convert it to PNG if needed.

**Comment by tnabtaf** [comment]
@Asmit2952 I understand.  The SVG is actually what I attached above, but it isn't rendering how I think it should.  I will send you both the SVG and a PNG outside of GitHub.
