### ISSUE TITLE
FAQ - Add How can I start using conda? question

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#47]
## Description

Add the question "How can I start using conda?" to the conda.org FAQ (docs/faq.md) and answer it. This answer could start with "There are several ways of getting conda in your computer... (link to Installation page)"

**Comment by travishathaway** [comment]
This is should also account for installing conda compatible tools like "mamba".

**Comment by deepeshaburse** [comment]
@travishathaway Sure, thank you for the review! I'll add that to the answer.

**Comment by sitamgithub-MSIT** [comment]
@travishathaway @kathatherine Is the issue work still not done? If not can you allow me to contribute?
