### ISSUE TITLE
FAQ - Add Why does conda have so many meanings in different contexts? question

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#48]
## Description

Add the question "Why does conda have so many meanings in different contexts?" to the conda.org FAQ (docs/faq.md) and answer it.

**Comment by travishathaway** [comment]
@kathatherine, I'm little curious to know about these different contexts. What exactly did you have in mind?

**Comment by kathatherine** [comment]
Oh, this was a question suggestion from @jaimergp. Maybe he can elaborate?

**Comment by jaimergp** [comment]
`conda` can be found as a noun and adjective in:

- conda, the tool
- conda packages
- conda environments
- conda channels
- conda, the package format
- conda, but you actually mean miniconda, the distribution, or one of its variants
- conda, the community, but maybe you are trying to refer conda-forge or bioconda?
- conda, the tool, but you are using mamba
- "I have a problem installing this conda package" - are you installing `conda` itself, or are you trying to install another package using `conda` to do so?
- conda, the package specification (the contents of each archive once extracted, regardless the compression format)

... to name a few. There are probably more :D

**Comment by deepeshaburse** [comment]
Hi @kathatherine @jaimergp, I'd like to give this issue a shot!
