### ISSUE TITLE
FAQ - Add How is the conda community organized? question

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#52]
## Description

Add the question "How is the conda community organized?" to the conda.org FAQ (docs/faq.md) and answer it.

**Comment by travishathaway** [comment]
Possible answer:

> Please read the "community" page to learn all about the conda community and how it's organized.

**Comment by Aadi1605** [comment]
hey I m interested ...Can I work on this?

**Comment by kathatherine** [comment]
Please feel free to submit a PR to this issue, @Aadi1605

**Comment by Shreyas-SAS** [comment]
hey, sorry to reply late! I am nearly done with this issue so @Aadi1605 please don't start working on it. I will push the PR in another 15 minutes or so. Have some issue with the branch on my side of the fork.
