### ISSUE TITLE
FAQ - Add Where can I find help? question

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#53]
## Description

Add the question "Where can I find help?" to the conda.org FAQ (docs/faq.md) and answer it.

**Comment by ankushbhardwaj408** [comment]
Hi @kathatherine i want to work on this issue ,can you please assign me this.

**Comment by ankushbhardwaj408** [comment]
Hi @kathatherine I have added the required faq section. Please review the PR #84

**Comment by travishathaway** [comment]
Thanks for taking this initiative on this @ankushbhardwaj408.

**Comment by ankushbhardwaj408** [comment]
Thanks @travishathaway for the all the suggestions. Please assign me some more issues so that i can contribute to Conda and improve my skills.
