### ISSUE TITLE
Add meetings calendar to "community" page

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#59]
## Description

The community page should have an embedded calendar listing all conda community meetings (conda, conda-forge, etc.). This will be a simple Google Calendar and should be execute very similarly to Nebari's community page: https://www.nebari.dev/docs/community#community-meetings

## Tasks

- [x] Create a Google Calendar for these meetings; initially we can just list the conda and conda-forge community meetings 
- [x] Embed it on the "community" page

**Comment by jaimergp** [comment]
More inspiration: https://www.cncf.io/calendar/

**Comment by bupd** [comment]
I would like to contribute. Can you assign this to me.

**Comment by travishathaway** [comment]
Hi @bupd,

I am going to be working on this issue. If you would like to become a contributor, I invite you to join our chat room: https://matrix.to/#/#conda.org:matrix.org

There, you will be able to reach out directly to us and find a task that would be reasonable for you to work on.
