### ISSUE TITLE
Broken link in Community page

### ISSUE THREAD

**Issue by kathatherine** [conda-incubator/conda-dot-org#67]
## Description

![image](https://user-images.githubusercontent.com/90850002/222193797-18f27d7e-ae70-48e4-8cc4-d4fb57bf6f47.png)

The Contributing section has a broken link to the GitHub Project page.

**Comment by travishathaway** [comment]
Thanks for reporting this. It has been fixed:

- https://github.com/conda-incubator/conda-dot-org/pull/62
