### ISSUE TITLE
Write a beginner friendly article on how to use conda-build

### ISSUE THREAD

**Issue by travishathaway** [conda-incubator/conda-dot-org#91]
## Description

In order to help spread educational content on conda-build, we would like to add a new blog post on how to use it. The blog post should describe how to build a non-trivial Python package with conda-build. By non-trivial, I mean a package that includes a C/C++ dependency to show the benefits of using conda.

## Tasks

- [ ] Write a new blog article on how to use conda-build.

**Comment by deepeshaburse** [comment]
Hi, I'd like to work on this.

**Comment by Shreyas-SAS** [comment]
@travishathaway can you please tell me the format and place the contribution needs to be pushed in? I have made a rough article template that can be viewed [here](https://pickle-creature-347.notion.site/Guide-to-Building-Python-Packages-with-Conda-build-Managing-C-C-Dependencies-Made-Easy-374f59e5691447bcadbf620b7c45f5c4). Please tell me whether I should convert it to a .md format or keep it as text. 

Additionally, can you please assign the issue to me to avoid clashes? Thanks.

**Comment by vasvi-sood** [comment]
Could you assign this issue to me. I'm familiar with the docusaurus technology and I think can write an informative blog post.

**Comment by travishathaway** [comment]
Hi all,

I have decided to assign this issue to @kathatherine. Thank you all for your interest in working on this. Please keep an eye on new issues with the label, "good-first-issue" for ones that we need help with.

**Comment by vasvi-sood** [comment]
> Hi all,
> 
> I have decided to assign this issue to @kathatherine. Thank you all for your interest in working on this. Please keep an eye on new issues with the label, "good-first-issue" for ones that we need help with.

I have spent a lot of time on research and already opened a pull request for this issue. Could you please review that. I can make changes if @kathatherine suggests any.
