### ISSUE TITLE
[docs]: Add Docs for `/learn/intro/` Page

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [conda-incubator/conda-dot-org#99]
## Description

Add docs to the  `/learn/intro/` page. 

![image](https://user-images.githubusercontent.com/67458417/233557296-ef9d3c41-851b-4fb9-bbe8-5325b5c6efcd.png)

## Tasks

- [ ] *Please add all tasks that need to be completed as part of this issue*

**Comment by SanjaySinghRajpoot** [comment]
I would like to work on this issue.

**Comment by travishathaway** [comment]
@SanjaySinghRajpoot,

We have removed this page, so this issue no longer makes sense. I will be closing it now.
